# Generated by Django 4.2 on 2024-03-15 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Team4',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no', models.CharField(max_length=100)),
                ('name1', models.CharField(max_length=100)),
                ('rollno1', models.CharField(max_length=20)),
                ('name2', models.CharField(max_length=100)),
                ('rollno2', models.CharField(max_length=20)),
                ('name3', models.CharField(max_length=100)),
                ('rollno3', models.CharField(max_length=20)),
                ('name4', models.CharField(max_length=100)),
                ('rollno4', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Team5',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no', models.CharField(max_length=100)),
                ('name1', models.CharField(max_length=100)),
                ('rollno1', models.CharField(max_length=20)),
                ('name2', models.CharField(max_length=100)),
                ('rollno2', models.CharField(max_length=20)),
                ('name3', models.CharField(max_length=100)),
                ('rollno3', models.CharField(max_length=20)),
                ('name4', models.CharField(max_length=100)),
                ('rollno4', models.CharField(max_length=20)),
                ('name5', models.CharField(max_length=100)),
                ('rollno5', models.CharField(max_length=20)),
            ],
        ),
    ]
